### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by anikki40** [ForlaxPy/BABAX-Stealer#1]
Please can you show me how to set this up? We can chat via ICQ or wherever you want so you can show me how to set it up and also how it works well.

**Comment by ForlaxPy** [comment]
Load the project to visual studio then go to DebuggerStepThroughAttribute/AssemblyCopyrightAttribute.cs 
Lines #25 and #26 put your bot and chat id of Telegram. Then compile-Obfuscate-crypt it and feel free to use.

**Comment by ALEHACKsp** [comment]
where do the files go?
